"""Страны и города сети: названия для людей, страна города, местные написания.

Справочник точек хранит город кодом источника (`tbilisi`, `novisad`,
`starazagora`), а страну — кодом ISO 3166-1 (`GE`). Код остаётся ключом везде;
здесь — как его показать (`COUNTRIES`, `CITIES`), в какой стране город
(`CITY_COUNTRY`) и как ещё его пишут люди (`CITY_SPELLINGS`, сверх русского и
английского названий), чтобы написанное на любом языке сводилось к английскому
имени точки (D233, `unit_name.py`).

Общее для бота и админки, поэтому живёт в `domain`. Новая страна или город
сети — строка сюда.
"""

from __future__ import annotations

COUNTRIES: dict[str, dict[str, str]] = {
    "AE": {"ru": "ОАЭ", "en": "UAE"},
    "AM": {"ru": "Армения", "en": "Armenia"},
    "AZ": {"ru": "Азербайджан", "en": "Azerbaijan"},
    "BG": {"ru": "Болгария", "en": "Bulgaria"},
    "CY": {"ru": "Кипр", "en": "Cyprus"},
    "EE": {"ru": "Эстония", "en": "Estonia"},
    "ES": {"ru": "Испания", "en": "Spain"},
    "GE": {"ru": "Грузия", "en": "Georgia"},
    "HR": {"ru": "Хорватия", "en": "Croatia"},
    "ID": {"ru": "Индонезия", "en": "Indonesia"},
    "KG": {"ru": "Кыргызстан", "en": "Kyrgyzstan"},
    "LT": {"ru": "Литва", "en": "Lithuania"},
    "ME": {"ru": "Черногория", "en": "Montenegro"},
    "MN": {"ru": "Монголия", "en": "Mongolia"},
    "NG": {"ru": "Нигерия", "en": "Nigeria"},
    "PL": {"ru": "Польша", "en": "Poland"},
    "QA": {"ru": "Катар", "en": "Qatar"},
    "RO": {"ru": "Румыния", "en": "Romania"},
    "RS": {"ru": "Сербия", "en": "Serbia"},
    "SI": {"ru": "Словения", "en": "Slovenia"},
    "TJ": {"ru": "Таджикистан", "en": "Tajikistan"},
    "TR": {"ru": "Турция", "en": "Türkiye"},
}

CITIES: dict[str, dict[str, str]] = {
    "abuja": {"ru": "Абуджа", "en": "Abuja"},
    "adana": {"ru": "Адана", "en": "Adana"},
    "antalya": {"ru": "Анталья", "en": "Antalya"},
    "baku": {"ru": "Баку", "en": "Baku"},
    "bali": {"ru": "Бали", "en": "Bali"},
    "bar": {"ru": "Бар", "en": "Bar"},
    "batumi": {"ru": "Батуми", "en": "Batumi"},
    "beograd": {"ru": "Белград", "en": "Belgrade"},
    "bishkek": {"ru": "Бишкек", "en": "Bishkek"},
    "brasov": {"ru": "Брашов", "en": "Brașov"},
    "bucuresti": {"ru": "Бухарест", "en": "Bucharest"},
    "budva": {"ru": "Будва", "en": "Budva"},
    "burgas": {"ru": "Бургас", "en": "Burgas"},
    "doha": {"ru": "Доха", "en": "Doha"},
    "dubai": {"ru": "Дубай", "en": "Dubai"},
    "dushanbe": {"ru": "Душанбе", "en": "Dushanbe"},
    "gyumri": {"ru": "Гюмри", "en": "Gyumri"},
    "iasi": {"ru": "Яссы", "en": "Iași"},
    "izmir": {"ru": "Измир", "en": "İzmir"},
    "kaunas": {"ru": "Каунас", "en": "Kaunas"},
    "klaipeda": {"ru": "Клайпеда", "en": "Klaipėda"},
    "koper": {"ru": "Копер", "en": "Koper"},
    "lagos": {"ru": "Лагос", "en": "Lagos"},
    "limassol": {"ru": "Лимасол", "en": "Limassol"},
    "ljubljana": {"ru": "Любляна", "en": "Ljubljana"},
    "manisa": {"ru": "Маниса", "en": "Manisa"},
    "menemen": {"ru": "Менемен", "en": "Menemen"},
    "mersin": {"ru": "Мерсин", "en": "Mersin"},
    "nicosia": {"ru": "Никосия", "en": "Nicosia"},
    "novisad": {"ru": "Нови-Сад", "en": "Novi Sad"},
    "parnu": {"ru": "Пярну", "en": "Pärnu"},
    "pleven": {"ru": "Плевен", "en": "Pleven"},
    "plovdiv": {"ru": "Пловдив", "en": "Plovdiv"},
    "podgorica": {"ru": "Подгорица", "en": "Podgorica"},
    "popeshtileordeni": {"ru": "Попешти-Леордени", "en": "Popești-Leordeni"},
    "sabadell": {"ru": "Сабадель", "en": "Sabadell"},
    "starazagora": {"ru": "Стара-Загора", "en": "Stara Zagora"},
    "tallinn": {"ru": "Таллин", "en": "Tallinn"},
    "tartu": {"ru": "Тарту", "en": "Tartu"},
    "tbilisi": {"ru": "Тбилиси", "en": "Tbilisi"},
    "ulaanbaatar": {"ru": "Улан-Батор", "en": "Ulaanbaatar"},
    "vilnius": {"ru": "Вильнюс", "en": "Vilnius"},
    "warszawa": {"ru": "Варшава", "en": "Warsaw"},
    "yerevan": {"ru": "Ереван", "en": "Yerevan"},
    "zagreb": {"ru": "Загреб", "en": "Zagreb"},
}

#: Страна города — код ISO 3166-1 alpha-2.
CITY_COUNTRY: dict[str, str] = {
    "abuja": "NG",
    "adana": "TR",
    "antalya": "TR",
    "baku": "AZ",
    "bali": "ID",
    "bar": "ME",
    "batumi": "GE",
    "beograd": "RS",
    "bishkek": "KG",
    "brasov": "RO",
    "bucuresti": "RO",
    "budva": "ME",
    "burgas": "BG",
    "doha": "QA",
    "dubai": "AE",
    "dushanbe": "TJ",
    "gyumri": "AM",
    "iasi": "RO",
    "izmir": "TR",
    "kaunas": "LT",
    "klaipeda": "LT",
    "koper": "SI",
    "lagos": "NG",
    "limassol": "CY",
    "ljubljana": "SI",
    "manisa": "TR",
    "menemen": "TR",
    "mersin": "TR",
    "nicosia": "CY",
    "novisad": "RS",
    "parnu": "EE",
    "pleven": "BG",
    "plovdiv": "BG",
    "podgorica": "ME",
    "popeshtileordeni": "RO",
    "sabadell": "ES",
    "starazagora": "BG",
    "tallinn": "EE",
    "tartu": "EE",
    "tbilisi": "GE",
    "ulaanbaatar": "MN",
    "vilnius": "LT",
    "warszawa": "PL",
    "yerevan": "AM",
    "zagreb": "HR",
}

#: Как ещё пишут город: местным алфавитом, с диакритикой, по-старому.
CITY_SPELLINGS: dict[str, tuple[str, ...]] = {
    "antalya": ("Анталия",),
    "baku": ("Bakı",),
    "batumi": ("ბათუმი",),
    "beograd": ("Beograd", "Београд"),
    "bishkek": ("Бишкек",),
    "brasov": ("Brașov", "Брашов"),
    "bucuresti": ("București", "Bucuresti"),
    "budva": ("Будва",),
    "burgas": ("Бургас",),
    "doha": ("الدوحة",),
    "dubai": ("دبي",),
    "dushanbe": ("Душанбе",),
    "gyumri": ("Գյումրի", "Gumri"),
    "iasi": ("Iași",),
    "izmir": ("İzmir",),
    "klaipeda": ("Klaipėda",),
    "koper": ("Capodistria",),
    "limassol": ("Лимассол", "Lemesos", "Λεμεσός"),
    "nicosia": ("Lefkosia", "Λευκωσία"),
    "novisad": ("Novi Sad", "Нови Сад", "Новый Сад"),
    "parnu": ("Pärnu", "Пярну"),
    "pleven": ("Плевен",),
    "plovdiv": ("Пловдив",),
    "podgorica": ("Подгорица",),
    "popeshtileordeni": ("Popești-Leordeni", "Popesti-Leordeni"),
    "starazagora": ("Стара Загора",),
    "tallinn": ("Таллинн",),
    "tbilisi": ("თბილისი", "Tiflis"),
    "ulaanbaatar": ("Улаанбаатар", "Ulan Bator", "Улан Батор"),
    "warszawa": ("Warszawa", "Warsaw"),
    "yerevan": ("Երևան", "Erevan", "Yerevan"),
}
